# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_auto_20170301_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authentication',
            name='id',
        ),
        migrations.AlterField(
            model_name='authentication',
            name='email',
            field=models.EmailField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
