# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_delete_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Authentication',
        ),
    ]
