# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_app', '0005_delete_authentication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authentication',
            fields=[
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
